# Unique name for this workflow
name: On Push

# Definition when the workflow should run
on:
  workflow_dispatch:
  push:

# Jobs to be executed
jobs:
  format-check:
    uses: dschach/github-actions/workflows/on-push.yml@feature-on-push
