# Unique name for this workflow
name: On Push

# Definition when the workflow should run
on:
  workflow_dispatch:
  push:

# Jobs to be executed
jobs:
  format-check:
    uses: ./.github/workflows/prettier-verify.yml

  release-please:
    if: github.ref_name == 'main' && github.ref_type == 'branch'
    needs: format-check
    uses: ./.github/workflows/release-please.yml
    with:
      release-type: sfdx
      the-branch: main
    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN }}
