# Unique name for this workflow
name: On Push

# Definition when the workflow should run
on:
  workflow_dispatch:
  push:

# Jobs to be executed
jobs:
  format-check:
    uses: ./.github/workflows/prettier-verify.yml
