name: Lint LWC, Aura and Test

on:
  workflow_call:
    secrets:
      codecov-token:
        required: false
  workflow_dispatch:

jobs:
  format-lint-lwc-tests:
    name: Lint LWC, Aura and Test
    runs-on: ubuntu-latest
    steps:
      # Checkout the source code
      - name: 'Checkout source code'
        uses: actions/checkout@v4

      # Install Volta to enforce proper node and package manager versions
      #- name: 'Install Volta'
      #  uses: volta-cli/action@v4

      - name: 'Setup node'
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: 'Install NPM'
        run: npm ci

      # Lint LWC / Aura
      - name: 'Lint Lightning Web Components / Aura Components'
        run: npm run lint

      # LWC unit tests
      - name: 'Unit test Lightning Web Components'
        run: npm run test:unit:coverage

      # Upload code coverage data
      - name: 'Upload code coverage for LWC to Codecov.io'
        uses: codecov/codecov-action@v5
        with:
          flags: LWC
          token: ${{ secrets.CODECOV_TOKEN }}${{ secrets.codecov-token }}
