# Unique name for this workflow
name: On Push

# Definition when the workflow should run
on:
  workflow_dispatch:
  push:

# Jobs to be executed
jobs:
  format-check:
    uses: ./.github/workflows/prettier-verify.yml

  release-please:
    # runs only on push - not on workflow-dispatch
    if: github.ref_name == 'main' && github.ref_type == 'branch'
    needs: format-check
    uses: dschach/github-actions/.github/workflows/release-please.yml@main
    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN }}
