name: release-please
on:
  workflow_call:
    secrets:
      release-token:
        required: true
        description: 'The access token so Release Please can propagate workflows'
    #outputs:
    #  rp-outputs:
    #    value: ${{ jobs.release-please.outputs.release-action-outputs}}

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    #outputs:
    #  release-action-outputs: ${{ steps.release.outputs }}
    steps:
      - id: release
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.release-token }}
      - id: release-outputs
        run: echo "rp-outputs=${{ steps.release.outputs }}" >> $GITHUB_OUTPUT
      - name: Echo Release Created
        run: echo "${{ steps.release.outputs.releases_created }}"
