name: release-please
on:
  workflow_call:
    inputs:
      release-type:
        required: true
        type: string
        default: 'salesforce'
      the-branch:
        required: true
        type: string
        description: 'The branch used for this release'
        default: 'main'
    secrets:
      release-token:
        required: true
        description: 'The access token so Release Please can work'

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          token: ${{ secrets.release-token }}
          release-type: ${{ inputs.release-type }}
          default-branch: ${{ inputs.the-branch }}
