name: release-please
on:
  workflow_call:
    secrets:
      release-token:
        required: true
        description: 'The access token so Release Please can propagate workflows'

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.release-token }}
